### ISSUE TITLE
Doesn't work with latest Homebrew version of berkeley-db

### ISSUE THREAD

**Issue by jvsteiner** [jpmorganchase/constellation#28]
Looks like `constellation-enclave-keygen` expects berkeley-db v 6.1, which currently homebrew is installing v6.2

```jvsmb:cons jamie$ ./constellation-enclave-keygen node
dyld: Library not loaded: /usr/local/opt/berkeley-db/lib/libdb-6.1.dylib
  Referenced from: /Users/jamie/Code/cons/./constellation-enclave-keygen
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by patrickmn** [comment]
Will issue a new release in a few days that should address this.

For now, installing from source should still work (although it'll take longer.)

**Comment by vjrantal** [comment]
While waiting for the fix, this workaround seems to enable the basic functionality:

```
$ ln -s /usr/local/opt/berkeley-db/lib/libdb-6.2.dylib /usr/local/opt/berkeley-db/lib/libdb-6.1.dylib
```

**Comment by patrickmn** [comment]
The latest [0.1.0](https://github.com/jpmorganchase/constellation/releases/tag/v0.1.0) release is linked against berkeleydb-6.2.

**Comment by riceman33** [comment]
I'm getting this error when I try the latest release package for mac. I notice constellation-enclave-keygen is not part of latest release package. I sit no longer needed or is the old one still compatible to use?

constellation-node: DbException "dbEnv_set_lg_regionmax" (SYSTEM_ERROR (-262143296))

**Comment by patrickmn** [comment]
Did you compile from source or download the release binaries?

If compiled from source, could you tell me the output of `ldd constellation-node`?

**Comment by riceman33** [comment]
for constellation I used the release binaries. for quorum i compiled from source. This is the logs from constellation1:
appending output to nohup.out
2017 Jun-07 12:35:01861984 [INFO] Log level is LevelWarn
constellation-node: DbException "dbEnv_set_lg_regionmax" (SYSTEM_ERROR (-257949488))

**Comment by patrickmn** [comment]
Could you try this binary instead: https://github.com/jpmorganchase/constellation/releases/download/v0.1.0/constellation-0.1.0-ubuntu1604-uncompressed.tar.xz

It may be related to the latest binaries being packed with upx.

If that doesn't work either, please tell me which Linux you're on, and which version of the BerkeleyDB bindings you have installed.

**Comment by riceman33** [comment]
I'm on a mac so can you provide link for mac package please. I have berkeleydb v6.2.23 installed.

The constellation error seems to be preventing the constellation nodes from starting.

I think another bug might be that the quorum geth command doesn't recognize the new conf setting called 'socket'. It does pick it up if I use the old conf settings (socketPath), however as constellation node is not running, geth fails to start too.

**Comment by patrickmn** [comment]
Looks like there's an issue with berkeleydb 6.2. I have retracted the MacOS binaries for now. Hope to address it soon...

For the config, Quorum @ master will parse the new values, but for now you can put the old values `publicKeyPath` and `socketPath` at the bottom of the config and it should load cleanly in both.

**Comment by riceman33** [comment]
ok thanks

**Comment by patrickmn** [comment]
This is not a fix, but I have opened a PR that adds a `dir` storage engine, which would get around this problem in a development environment, at least temporarily: https://github.com/jpmorganchase/constellation/pull/38

If you check out that PR and follow the Compiling from source instructions, you should be able to set `storage="dir:path"`  in the config and avoid the BerkeleyDB errors.

**Comment by patrickmn** [comment]
@vjrantal Did symlinking 6.2 to the 6.1 dylib actually work for you? You didn't encounter the same errors?

I'm confused as to why that would work, but linking against 6.2 doesn't.

**Comment by vjrantal** [comment]
@patrickmn I should have been more specific in that I only tested `constellation-enclave-keygen` after the symlinking. In my case, I only required keys to be generated on a Mac since I run the `constellation-node` [on a Raspberry Pi](https://youtu.be/64kMWxTaXw8).

Now that I tested `constellation-node` on Mac, I see the same issue as discussed above:

```
constellation-node: DbException "dbEnv_set_lg_regionmax" (SYSTEM_ERROR (-1790964160))
```

**Comment by patrickmn** [comment]
Ok, thanks.

I'm honestly not sure what the best approach will be. There seem to be major changes in bdb 6.2, which is odd at least if they're supposed to be using semantic versioning. Perhaps we will need to bundle bdb <=6.1 or provide instructions on how to easily install it...

**Comment by patrickmn** [comment]
Several new storage engines are enabled in the latest master. It should be possible to link against berkeleydb but choose one of the other engines on Mac, for now.

`dir` is one such new engine that's certain to stay and be backwards-compatible.

From the CHANGELOG:

- A `dir` storage engine which stores payloads as individual files in
  a folder, suitable for use with FUSE connectors. (Note that, if used
  with Quorum and a distributed file system, it should have strong
  read-after-create consistency to avoid unexpected behavior. In other
  words, after a file is created, other nodes should immediately be
  able to read it.)

  The `dir` storage engine uses Base32-encoded filenames to ensure
  compatibility with most file systems.

- (Experimental) A 'sqlite' storage engine. See related discussion at
  https://github.com/jpmorganchase/constellation/issues/37

- (Experimental) A 'leveldb' storage engine. See related discussion at
  https://github.com/jpmorganchase/constellation/issues/37

- A non-persistent 'memory' storage engine.

- Ability to choose a storage engine in configs and on the command
  line:
    - `--storage=bdb:path`: `bdb` storage engine using the `path`
      folder.
    - `--storage=dir:path`: `dir` storage engine using the `path`
      folder.
    - `--storage=leveldb:path`: `leveldb` storage engine using the `path`
      folder.
    - `--storage=memory`: non-persistent `memory` storage engine.
    - `--storage=sqlite:path`: `sqlite` storage engine using the `path`
      folder.
    - `--storage=path`: Default storage engine (`bdb`) using the
      `path` folder.

**Comment by s-matthew-english** [comment]
so - I tried using `--storage=dir:path`, but for me it didn't work- maybe I've not done it in the right way? 

<img width="1440" alt="screen shot 2017-08-21 at 3 44 03 pm" src="https://user-images.githubusercontent.com/9053984/29535434-ce383f40-8687-11e7-8a95-a1ac444dfabc.png">

**Comment by cartazio** [comment]
should be resolved once https://github.com/jpmorganchase/constellation/pull/82 gets merrged in :)

**Comment by Tiny-zhongwen** [comment]
Why do I still show bugs with libdb-6.1.dylib? constellation-node is the oldest version on the web? How to solve this problem？

**Comment by Tiny-zhongwen** [comment]
How do you solve the problems that arise with constellation node on a MAC?

I wasted a long time just dealing with these pits. I'm breaking down. Also, why does constellation update only ubuntu on its official website and not MAC? This is unfair to Mac users.

Well, with all that said, I just don't know how to build a quorum on a MAC. Can you give me a little bit of advice?

**Comment by jpmsam** [comment]
@Tiny-zhongwen The new constellation version will have better Mac support. 

Quorum can be easily built on Macs:

`git clone https://github.com/jpmorganchase/quorum`
`cd quorum`
`make geth`

We are planning to have the same simple support in our updated constellation client.
